#!/usr/bin/python

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#Initialize an array for the Fibonacci numbers
fib=[1,2]

#Notice that fib[-1] returns the last element in an array
#fib[-2] returns the one before, etc...
current=0
while current < 4000000:
  current=fib[-1]+fib[-2]
  fib.append(current)

#Compute the sum
result=0
for x in fib:
  if x%2 == 0:
    result+=x

print result