#!/usr/bin/python

#How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?

from sets import Set

l = []
for a in range(2, 101):
  for b in range(2, 101):
    l.append(a**b)

print(len(Set(l)))